### ISSUE TITLE
Error changing target directory

### ISSUE THREAD

**Issue by shader** [skangas/mentor#12]
When I use the 'o' key to change the directory of a torrent I just added, I get the following error:

```
Debugger entered--Lisp error: (error "XML-RPC fault ‘Target of wrong type to command.’")
  signal(error ("XML-RPC fault ‘Target of wrong type to command.’"))
  async-handle-result(#f(compiled-function (remaining) #<bytecode 0x293a9d1>) (async-signal (error "XML-RPC fault ‘Target of wrong type to command.’")) #<buffer *emacs*>)
  async-when-done(#<process emacs> "finished\n")
```

**Comment by skangas** [comment]
Thanks for the bug report - now fixed!

**Comment by shader** [comment]
I tried using the latest version, but I ran into an error about no-move:
```
Debugger entered--Lisp error: (void-function no-move)
  (no-move)
  (cons 'no-move (no-move))
  (list (cons 'name (mentor-item-property 'name)) (cons 'was-started (= (mentor-item-property 'is_active) 1)) (cons 'hash (mentor-item-property 'hash)) (cons 'old old) (cons 'new new) (cons 'local_id (mentor-item-property 'local_id)) (cons 'no-move (no-move)))
```
I think it's because of
https://github.com/skangas/mentor/blob/753f69790dc8542d7651347ffb50b49d49e21213/mentor.el#L1262
which should probably just be `,no-move`
I changed it locally, and it seemed to work. Probably simpler for you to make the change than for me to make a PR.

**Comment by skangas** [comment]
I seem to have changed this by mistake in the last commit. I've pushed a fix now - thanks!
