### ISSUE TITLE
Option xmlrpc_dialect does not exist according to rtorrent

### ISSUE THREAD

**Issue by shader** [skangas/mentor#13]
When I try to run rtorrent (version 0.9.7) with the suggested .rtorrent.rc file, I get the following error:
```
rtorrent: Error in option file: ~/.rtorrent.rc:2: Command "xmlrpc_dialect" does not exist.
```
If I remove the one line, rtorrent runs, and mentor appears to be able to connect to it. However, I do get a variety of XML_RPC related errors, so perhaps not everything is as it should be? I'll post the other errors as separate issues.

**Comment by skangas** [comment]
It seems like this is no longer needed, so I'll just remove it. Thanks!

For reference:
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-network-xmlrpc-dialect-set
