### ISSUE TITLE
Difficulty adding magnet uri

### ISSUE THREAD

**Issue by shader** [skangas/mentor#14]
If I try to add a magnet uri (using `<del>`) that includes tracker information, the minibuffer input interprets the slashes as directory entries, and gives the following error:
```
Debugger entered--Lisp error: (file-missing "Opening input file" "No such file or directory" "/open.kickasstracker.com:443/announce")
  insert-file-contents("/open.kickasstracker.com:443/announce" nil nil nil nil)
  insert-file-contents-literally("/open.kickasstracker.com:443/announce")
  mentor-rpc-c-load-raw("/open.kickasstracker.com:443/announce" nil)
  mentor-download-add(nil)
  funcall-interactively(mentor-download-add nil)
  call-interactively(mentor-download-add nil nil)
  command-execute(mentor-download-add)
```
If I remove all of the trackers, it seems to accept the uri, but does not actually add anything to the list of torrents.

**Comment by skangas** [comment]
Hi, I'm having trouble reproducing this bug. Could you please send me the exact Magnet URI that caused this bug via e-mail? You can send it to my gmail.com address: stefankangas@...
