### ISSUE TITLE
Update for rTorrent v0.9.7+

### ISSUE THREAD

**Issue by shader** [skangas/mentor#15]
I wonder if my other issues aren't related to the following:

https://github.com/rakshasa/rtorrent/wiki/RPC-Migration-0.9

Apparently lots of commands now require a target, and many configuration terms have been deprecated for a long time and finally removed.

The link provides a sed file for updating things; maybe that could help with fixing mentor to work with the latest version?

**Comment by skangas** [comment]
Hi,

Thanks for the report. I'm pretty sure that I updated to the new API in aa65a24. Do you have reason to believe otherwise?

**Comment by shader** [comment]
It was more of a speculation related to my other issues, since one of them involved the target of the command, the rc file commands have changed, and the deprecation was rather recent.

Since you've already updated to the 0.9 API though, I guess my speculation was incorrect.

**Comment by skangas** [comment]
OK, no worries! Thanks for the bug reports.

**Comment by skangas** [comment]
Seems like I actually _had_ missed to update the configuration for 0.9. See #13 for reference. Thanks again!
