### ISSUE TITLE
magnet link support?

### ISSUE THREAD

**Issue by cryptomata** [skangas/mentor#5]
Is it possible to add a magnet link using mentor?

**Comment by cryptomata** [comment]
I added this little function locally, it's essentially what I wanted.

`
(defun mentor-load-normal (&optional arg)
  (interactive "Mload.normal: ")
  (mentor-rpc-command "load.normal" "" arg)
)
`

**Comment by skangas** [comment]
solarus implemented this (based on your work I guess) and it's now merged into master. Thanks for the feature suggestion!
