### ISSUE TITLE
no buffer named *mentor-term*

### ISSUE THREAD

**Issue by parjanya** [skangas/mentor#9]
Hi! I have just installed `mentor` via `melpa`, on GNU Emacs 26.0.50, which I compiled myself from trunk. I have `rtorrent` installed and working. If I do `M-x mentor RET` all I get is a jump to a buffer named `mentor`, and this message:

> `mentor-rtorrent-run-in-background: No buffer named *mentor-term*`

I’ve tried to do `(setq mentor-rtorrent-buffer-name "*mentor*")` but I got the message

> `mentor-setup-rtorrent: Wrong type argument: "Need a pre-parsed URL.", #s(url "scgi" nil nil "" nil "/home/edgard/.emacs.d/mentor/rtorrent.rpc" nil nil t ...), url`

So I checked and that file `rtorrent.rpc` was there. I’ve deleted it, and now rtorrent is working, and appearing on this `*mentor*` buffer.

I don’t know what I did here but it seems to have worked : o ). I guess the problem was just the `.rpc` file...?

Thanks for the package!

**Comment by ecraven** [comment]
I've also run into this same error, clean install of mentor from melpa.

**Comment by skangas** [comment]
Thanks for reporting this bug! I've now fixed it and pushed a new version. Please let me know if you have any further issues.
